services:
  beszel:
    image: henrygd/beszel:latest
    hostname: beszel
    restart: always
    volumes:
      - beszel:/beszel_data
      - /var/run/beszel_socket:/beszel_socket

    networks:
      - game_node_app_public

  beszel-agent:
    image: henrygd/beszel-agent:latest
    hostname: beszel-agent-1
    network_mode: host
    restart: always
    volumes:
      - /var/run/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      # UPDATE WITH YOUR PUBLIC KEY (copy from "Add system" dialog)
      KEY: ${AGENT_KEY}


networks:
  game_node_app_public:
    external: true

volumes:
  beszel: